### ISSUE TITLE
Stack level too deep when record has no href

### ISSUE THREAD

**Issue by mikecmpbll** [meritec/arbor-rb#13]
we assumed (fairly) that all records have a href. when they don't, however, the call to `href` hits the method_missing, which tries to load the full resource, which calls href .. and the loop begins.

if we add href to attr_accessor it won't hit method missing.

**Comment by nadrooJ** [comment]
> we assumed (fairly) that all records have a href. when they don't  

I think this has more to do with the permissions that they have introduced in their latest update. If we don't have permission to view a resource (or the linking resource) then, iirc, nothing is returned for that (not sure of any error messages in headers or anything)
